dist: bionic
os: linux
language: java
jdk:
  - openjdk8
services:
- docker

env:
  global:
    - secure: "PYYXFvJMIvi90us+54UNhKxV+mmBtrI/ODtmidw/sPuf0TaYCLxglGiVLMC5HL+8Y4lBD+bwwSwuPxhq09/mpZBavYk41RMNwB+xbPT8VxX3MJCQvq5uiuAhF+O3Kbo+5pSrZDVSJ2ZGwPwCTxngUfbNlgVTEotki2KQjPEccd78amCjMyAyhY7vvhggNeSEHl1qVreD75MUZrBKzsM64Uq85yWI1tA+axFoSq1gYnsO/+fzXaLBdPMvvAwiTJ/HpqwYFy0iJ895aD2/dJGV7etnzXB/mMNhofQZh8/LWbJay48D16crxY5bjFVn0jIx3Xx8ELTmhgq4NCVJW5NaZlzI0poKNEA2hCu+YOS6OQLJ7abY2MCeqA8mGp0mzOqtyCW8GLp55SO3dyIQpWv6puod/VLNkxrkimMyC2cnUie4WpiI9usnJ8UaKUigiZngLsThtIZVngKVN8pXux3Bkb91iGnqTF2/9gnO6MsguA8XiaZyKQJ28/9Ix7pId/4DJddHm5EtSWjXdK1K8wESO9pApEBoo98omZ7hwVYzqdZLzw9vp3s/YorpqQ4B2udcHKT/Q4+gpcr/H5HpVnyUJHHq3n4hep9boruviw1IKA5OtrAAvulWiInfKqQPPGsiNnUJvpMRC3W6hlpGdPJhdPzhBj4Qg+3o2sRb7kUCAjk="
    - secure: "JrF/YWvtNcmdkHDuZoGIteBIQHPx7M60u41BWkXKpM8yxOvvyoXXMylGXoBpzpG4dSHJDRdJLJE5FF6U7dnY/8eFV/n0FaeRXKluA1wG3egxmXiItO9REKXr5kXkXic5eDTFoz05E/4Veiwq5S9xoGJ7riofl1YbldAqzz+vVspaaAp9Ggzlx6WdM/m8/6c9H/LOoRQ0cOuVx+63ZI3a22LYN63+LixDAwrf6MGGGkiuieeQmTzX1PRkF+kaLcKruw8Ok/4KZOkERcOJLnpVNZpui+2MKf6rfeFn3AGXP0G8dUkm0kI0MOvgpBDr4we++00xsDudC1Ef2SyPQtlqLJIS9It+X5vJTMiZaOqvqJ9myRbH+tzEAz+OlbcNbvFj4s3Dq6Xmw9QPGD9Wd5FQ3jI0M3oXQXvZrw/FcfZk14G7VSZGdCdN+FHU9IKPUYSEmzduty9YFIf9+b8gpo9ZGKdNfP3+GMc4KoHKmkGT3Dse8V0a/S7MhYd8IF6S9F6P4I0yEfWQcVugJFNDl3uv7GbbIy1aqg74BDXqm9rM0vqDNj3iRWGlznpnmX+C2bCO6mn+9YMBhT0luBs4+MtUERBtdTuSqsVx3Bcnev7HcGOQzSOC5R4V0WfsSaDnA1bn0x9DkGfinAOInx6s9w4osqZe7zz151E9kuxb4/cmu58="

notifications:
  email:
    on_success: change
before_install:
  # login to docker at the very beginning, so we don't run into rate-limiting
  - java -version
  - |-
    if [ -n "$DOCKER_PASSWORD" ]
    then
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    fi

jobs:
  include:
  - stage: Run Build
    cache:
      directories:
      - "$HOME/.m2"
    script:
    - mvn -DskipTests -Dgpg.skip clean package
  - stage: Run Tests
    if: branch = main OR type = pull_request
    cache:
      directories:
      - "$HOME/.m2"
    install:
    - docker-compose -f src/test/resources/docker-compose-test.yaml pull
    script:
    - mvn clean test -Dgpg.skip
  - stage: Deploy Artifacts
    if: tag IS present
    branches:
      only:
      - main
    cache:
      directories:
      - "$HOME/.m2"
    before_install:
    - openssl aes-256-cbc -K $encrypted_3b9f0b9d36d1_key -iv $encrypted_3b9f0b9d36d1_iv -in .secrets.tar.enc -out secrets.tar -d
    - tar xvf secrets.tar
    - cp settings.xml $HOME/.m2/
    - gpg --batch --import key.gpg
    - export GPG_TTY=$(tty)
    install:
    - docker-compose -f src/test/resources/docker-compose-test.yaml pull
    script:
    - mvn deploy
